export const PROFILE = {
  name: "PECO XU",
  title: "Content Producer | Technical Artist",
  quote: "从杭州浙传到伦敦 UCL，在数字媒体领域“打怪升级”多年，也在腾讯&网易死磕过 S 级项目——我依然是个热衷新技术的 ACG 玩家。正试着用数字叙事的专业逻辑，给内容宣发叠个“有趣”的 Buff。",
  avatar: "https://picsum.photos/seed/avatar/400/400",
  bio: "我热衷于S 级项目中死磕视觉细节，也习惯在高频次产出中寻找商业平衡。曾带领过数十人团队从 0 到 1 做出过百万播放。比起重复劳动，我更想用新工具和新技术玩点不一样的内容。",
  aboutHighlights: [
    { company: "Tencent IEG", role: "创意内容策划", description: "暗区突围、火影忍者" },
    { company: "NetEase Games", role: "视频设计", description: "一梦江湖、第五人格" },
    { company: "CUZ Official B 站", role: "创始人 / 站长", description: "160 万 + 累计播放" },
    { company: "央视融媒", role: "后期视效包装", description: "国家级重大选题" },
  ],
  birthday: "2000 / 01 / 01",
  location: "四川 成都",
  email: "abcaabc@foxmail.com",
  phone: "+86 12354212335",
  education: [
    { school: "伦敦大学学院", degree: "硕士", major: "Digital Media: Production" },
    { school: "浙江传媒学院", degree: "本科", major: "数字媒体艺术" },
  ],
  capabilities: [
    {
      category: "宣发监修",
      skills: ["S 级项目视觉监修", "工业化 SOP 建设", "外部供应商统筹", "商业视觉表现把控"],
    },
    {
      category: "美术技术",
      skills: [
        "游戏引擎实时渲染",
        "AI 工作流优化",
        "专业影视摄制技术",
        "交互式数字叙事",
      ],
    },
    {
      category: "内容编导",
      skills: ["百万流量孵化", "ACG 核心圈层洞察", "脚本与分镜撰写", "全案编导执行力"],
    },
  ],
  techStack: [
    { name: "Photoshop", icon: "https://res.cloudinary.com/di8s8kt8a/image/upload/v1772283874/Adobe_Photoshop_CC_icon_koelqy.png", usage: "图片处理" },
    { name: "Blender", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/blender/blender-original.svg", usage: "三维建模" },
    { name: "After Effects", icon: "https://res.cloudinary.com/di8s8kt8a/image/upload/v1772283874/Adobe_After_Effects_CC_icon_tlf1o5.png", usage: "特效制作" },
    { name: "ComfyUI", icon: "data:image/svg+xml;charset=utf-8,%3Csvg width='24' height='24' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Crect x='2' y='4' width='6' height='6' rx='1' fill='%233B82F6'/%3E%3Crect x='16' y='4' width='6' height='6' rx='1' fill='%2310B981'/%3E%3Crect x='9' y='14' width='6' height='6' rx='1' fill='%238B5CF6'/%3E%3Cpath d='M5 10V12C5 13.1046 5.89543 14 7 14H9' stroke='%239CA3AF' stroke-width='2' stroke-linecap='round'/%3E%3Cpath d='M19 10V12C19 13.1046 18.1046 14 17 14H15' stroke='%239CA3AF' stroke-width='2' stroke-linecap='round'/%3E%3C/svg%3E", usage: "AI工具" },
    { name: "Unreal Engine 5", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/unrealengine/unrealengine-original.svg", usage: "游戏引擎" },
    { name: "Framer", icon: "data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='black'%3E%3Cpath d='M4 0h16v8h-8zM4 8h8l8 8H4zM4 16h8v8z'/%3E%3C/svg%3E", usage: "网页设计" },
  ],
  experience: [
    {
      role: "技术美术",
      company: "CIGA GameJam",
      year: "2022 — 2023",
      description: "连续两年参与 48h 高强度游戏开发挑战，负责游戏引擎内的资源集成与跨职能研发协作。独立完成实机演示 PV 的视觉包装与剪辑，助力团队在极短时间内实现高品质 Demo 交付与路演展示。"
    },
    {
      role: "创意内容策划",
      company: "腾讯互娱（IEG）",
      year: "2021",
      description: "参与《暗区突围》、《火影忍者手游》等 S 级项目首发，主导 UE4 动画 PV 监修并严控视听表现，对齐顶级 IP 视觉标准。主导电竞赛事 Motion Graphics 动态包装，深度参与百万播放角色 PV 剪辑与工作室品牌 Logo 动态升级。"
    },
    {
      role: "视频设计",
      company: "网易互娱",
      year: "2020",
      description: "负责《一梦江湖》等头部游戏项目商业化买量视频的从分镜到后期的全链路制作。搭建高效的个人产出管线，保持周均 15 条以上的高质量物料输出，突出视觉表现力有力支撑市场投放消耗。"
    },
    {
      role: "站长 / 创始人",
      company: "浙传官方 Bilibili",
      year: "2019 — 2021",
      description: "从 0 到 1 统筹孵化官方新媒体内容矩阵，组建并管理 50 人以上全媒体运营团队。搭建高效的内容生产 SOP 体系，主导千万级头部联动企划摄制，实现账号粉丝自然增长与超 160 万 + 累计播放量。"
    },
    {
      role: "后期视效包装",
      company: "央视融媒体中心",
      year: "2018 — 2021",
      description: "深度参与进博会、国庆阅兵等国家级重大新闻选题的视觉包装与后期制作，产出内容成功登陆 CCTV-13 新闻频道。严格遵循广电级播出标准，运用 Motion Graphics 动态设计打造 B 站百万级爆款传播内容。"
    }
  ],
  awards: [
    { title: "优秀毕业生", event: "浙江传媒学院", year: "2023" },
    { title: "大学生多媒体大赛二等奖", event: "浙江传媒学院", year: "2022" },
    { title: "二等奖学金", event: "浙江传媒学院", year: "2020 / 2021" },
    { title: "三等奖学金", event: "浙江传媒学院", year: "2019 / 2020" },
    { title: "全媒体中心优秀干部", event: "浙江传媒学院", year: "2020" },
    { title: "艺术团优秀干部", event: "浙江传媒学院", year: "2020" },
    { title: "优秀团员", event: "浙江传媒学院", year: "2020" },
    { title: "第六届大学生新闻节其他类优胜奖", event: "浙江省", year: "2019" },
  ],
};

export const CATEGORIES = ["All", "Motion", "Tech Art", "Interactive"];

export const PROJECTS = [
  {
    id: "1",
    title: "暗区突围：\n硬核视觉体系",
    subtitle: "Arena Breakout",
    category: "Motion",
    cover: "https://video.pecoxu.me/d/Portfolio/01%20Arena%20Breakout/cover1.jpg",
    year: "2021",
    role: "创意内容策划",
    client: "腾讯 IEG 魔方工作室群",
    challenge:
      "**硬核 S 级产品**公测初期**上手门槛极高**，玩家亟需系统化的**官方教学资源**辅助认知与留存。同时，**外部供应商**对项目调性理解不足，需在高频宣发中强化**风格管控与监修**，确保赛事包装与**品牌视觉**高度契合。",
    solution:
      "· **内容脚本创作：** 深度参与S级硬核项目**《暗区突围》官方内容矩阵脚本**，通过**系统化内容逻辑**拆解高门槛玩法，实现从“硬核产品”到“大众认知”的精准转化。\n· **实机动画质量监修：** 重点负责**UE4引擎动画**的质量监修，通过**审美引导与 SOP 确立**，确保外部供应商对齐项目硬核调性。\n· **赛事视觉风格把控：** 独立完成**“黄金周电竞赛事”**的包装迭代，通过专业意见输出与后期修正，确保最终视觉效果**高度契合**品牌硬核调性。",
    outcome: "· **业务价值转化：** 全程支撑项目公测初期的**全渠道营销活动**，构建教学内容矩阵，累计播放量**300,000+**，显著助力玩家留存。\n· **工业化提效：** 确立**监修标准与生产流程**，有效降低了与供应商的沟通成本，使项目整体生产效率提升约 **30%**。",
    media: [
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/01%20Arena%20Breakout/video1_1.mp4', title: '暗区快报 容器系统篇', aspectRatio: '16/9' },
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/01%20Arena%20Breakout/video1_2.mp4', title: '暗区突围 黄金周赛', aspectRatio: '16/9' },
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/01%20Arena%20Breakout/video1_3.mp4', title: '暗区突围指南', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/01%20Arena%20Breakout/pic1_1.jpg', title: '暗区快报  容器系统篇', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/01%20Arena%20Breakout/pic1_2.jpg', title: '暗区快报  容器系统篇', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/01%20Arena%20Breakout/pic1_3.jpg', title: '暗区突围 黄金周赛   包装设计', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/01%20Arena%20Breakout/pic1_4.jpg', title: '暗区突围 黄金周赛   包装设计', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/01%20Arena%20Breakout/pic1_5.jpg', title: '暗区突围指南', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/01%20Arena%20Breakout/pic1_6.jpg', title: '暗区突围指南', aspectRatio: '16/9' },
    ],
  },
  {
    id: "2",
    title: "火影忍者：\n全案动态设计",
    subtitle: "Naruto Mobile",
    category: "Motion",
    cover: "https://video.pecoxu.me/d/Portfolio/02%20Naruto/cover2.jpg",
    year: "2021",
    role: "创意内容策划",
    client: "腾讯 IEG 魔方工作室群",
    challenge:
      "针对顶级二次元 IP 的线下复杂赛制与核心角色宣发，需在确保 **IP 调性一致性**的前提下，实现赛制信息的**极简传导**。同时，S 级核心角色宣发对**视听张力**要求极高，需通过极致的**节奏把控**还原角色压迫感，并有效驱动**社区自发传播**。",
    solution:
      "· **赛事动态可视化监修：** 全程监修城市赛系列视频的 **Motion Graphics** 设计，通过**模块化视觉**重构赛制流程，确保跨媒介呈现的专业感与品牌张力，提升信息触达效率。\n· **S 级角色 PV 节奏把控：** 深度参与**“佩恩”角色视频**的剪辑节奏与镜头衔接，运用高标准的**视听语言**精准对齐 **IP 监修标准**，深度还原角色性格魅力。",
    outcome: "· **赛事高标准落地：** 成功护航多站**大型线下赛事**落地，以清晰的逻辑与高级的视觉风格获得业务方高度认可，确立了 IP 在竞技场景下的视觉标准。\n· **百万级现象传播：** 助力角色 PV 实现 B 站单平台播放量 **1,000,000+**，成为阶段性爆款内容，显著提升了核心玩家的活跃度与品牌搜索指数。",
    media: [
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/02%20Naruto/video2_1.mp4', title: '城市赛赛程赛制全知道', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/02%20Naruto/pic2_1.jpg', title: '城市赛PV LOGO', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/02%20Naruto/pic2_2.jpg', title: '城市赛PV 城市介绍', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/02%20Naruto/pic2_3.jpg', title: '城市赛PV大标题', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/02%20Naruto/pic2_4.jpg', title: '城市赛PV赛制介绍', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/02%20Naruto/pic2_5.jpg', title: '城市赛PV奖金介绍', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/02%20Naruto/pic2_6.jpg', title: '城市赛PV赛制介绍', aspectRatio: '16/9' },
    ],
  },
  {
    id: "3",
    title: "网易游戏：\n效果创意与品牌推广",
    subtitle: "NetEase Games",
    category: "Motion",
    cover: "https://video.pecoxu.me/d/Portfolio/03%20NetEase/cover3.png",
    year: "2020",
    role: "视频设计",
    client: "网易互娱 设计中心",
    challenge:
      "针对**《神都夜行录》**等头部项目，需在**极短生产周期**内产出**高点击率的买量视频**以支撑高频市场投放。同时，需针对**《一梦江湖》**等 IP 的衍生品进行**商业化推广**，通过视觉包装缩短与年轻玩家的距离。",
    solution:
      "· **全链路高效生产：** 独立承担从脚本分镜到后期合成的**全链路买量视频制作**，通过**建立模块化素材库**提升产出效率，稳定支撑了每周 **15 条**以上的高频投放需求。\n· **潮流视觉包装：** 基于**“黄金 3 秒”**法则优化视频开篇，并针对不同渠道的受众偏好进行**多套素材**的测试实验，根据反馈快速迭代内容。",
    outcome: "· **千万级投放支撑：** 有力支撑了千万级预算的市场消耗，通过创意的不断优化，显著提升了**广告的转化效率与投资回报率（ROI）**。\n· **商业化变现赋能：** 高质量的视觉呈现成功赋能 **IP 衍生品**的销售推广，大幅提升了品牌在年轻玩家群体中的**认可度与购买转化**。",
    media: [
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/03%20NetEase/video3_1.mp4', title: '一梦江湖 潮流单品 PV', aspectRatio: '16/9' },
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/03%20NetEase/video3_2.mp4', title: '一梦江湖 买量视频', aspectRatio: '9/16' },
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/03%20NetEase/video3_3.mp4', title: '一梦江湖 买量视频', aspectRatio: '9/16' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/03%20NetEase/pic3_1.jpg', title: '一梦江湖 潮流单品PV', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/03%20NetEase/pic3_2.jpg', title: '一梦江湖 潮流单品PV', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/03%20NetEase/pic3_3.jpg', title: '一梦江湖 潮流单品PV', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/03%20NetEase/pic3_4.jpg', title: '一梦江湖 潮流单品PV', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/03%20NetEase/pic3_5.jpg', title: '一梦江湖 买量视频', aspectRatio: '9/16' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/03%20NetEase/pic3_6.jpg', title: '一梦江湖 买量视频', aspectRatio: '9/16' },
    ],
  },
  {
    id: "4",
    title: "浙传 B 站：\n百万爆款孵化",
    subtitle: "CUZ Bilibili",
    category: "Interactive",
    cover: "https://video.pecoxu.me/d/Portfolio/04%20CUZBilibili/cover4.png",
    year: "2021",
    role: "创始人 / 站长",
    client: "浙江传媒学院 全媒体中心",
    challenge:
      "需从零构建高校官方新媒体阵地，平衡校级官媒的**权威性**与 B 站受众对**爆款内容**的审美偏好。在多方协作环境下，如何统筹跨校、跨机构资源并产出具备**圈层影响力**的内容是核心难题。",
    solution:
      "· **团队构建与全链路管理：** **从 0 到 1** ，创立并统筹 **55 人**规模的学生新媒体团队，确立了从人员招募、技能教学到内容产出的**全链路管理 SOP**。\n· **跨机构深度制片：** 以制片人及导演身份联合**共青团中央、B 站官方及多所名校**，统筹了 **2021 BDF** 等多项头部内容的创意策划与落地，实现了官方叙事在年轻群体中的成功转译。\n· **深度洞察 B 站社区生态与算法：** 通过对二次元受众审美偏好的持续研究，精准捕捉社区热点，在内容生产中埋入传播点，显著提升了内容的**自发传播率**。",
    outcome: "· **爆款内容产出：** 成功孵化多支现象级视频，累计播放量 **1,600,000+**，实现单支视频最高 **1,200,000+** 播放的传播表现。\n· **品牌增长与矩阵确立：** 账号粉丝量实现**从 0 到 20,000+** 的突破，构建了具备高度社会化传播声量的**学校官方媒体矩阵**，提升了学校官方在年轻圈层中的品牌影响力。",
    media: [
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/04%20CUZBilibili/video4_1_4k.mp4', title: 'BDF向阳', aspectRatio: '16/9' },
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/04%20CUZBilibili/video4_2_4k.mp4', title: '江山行歌', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/04%20CUZBilibili/pic4_1.jpg', title: '浙传B站主页', aspectRatio: '9/16' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/04%20CUZBilibili/pic4_2.jpg', title: 'BDF数据', aspectRatio: '9/16' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/04%20CUZBilibili/pic4_3.jpg', title: 'BDF向阳', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/04%20CUZBilibili/pic4_4.jpg', title: '向阳_片尾', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/04%20CUZBilibili/pic4_5.png', title: '江山行歌', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/04%20CUZBilibili/pic4_6.jpg', title: '江山行歌_片尾', aspectRatio: '16/9' },
    ],
  },
  {
    id: "5",
    title: "浙传央视融媒：\n官方品牌叙事",
    subtitle: "CCTV x CUZ",
    category: "Motion",
    cover: "https://video.pecoxu.me/d/Portfolio/05%20CUZCCTV/cover5.png",
    year: "2021",
    role: "后期视效包装",
    client: "浙江传媒学院 央视融媒体中心",
    challenge:
      "在**国家级题材**的严苛审核标准下，探索如何平衡官方叙事的严肃性与 B 站等社交平台的**年轻化表达**。核心难点在于如何通过**视觉逻辑**，将深度、复杂的专题报道转化为易于在年轻人中传播的**现象级内容**。",
    solution:
      "· **实现官方内容的年轻化转译：** 参与央视新闻 B 站专题**《起底美国疫情》**的 **MG 动效与插图设计**，运用极具节奏感的视觉语言，将复杂的深度报道内容转化为符合年轻人审美偏好的动态视觉作品。\n· **对齐行业顶级视效标准：** 深度参与多项**国家级重大选题**的后期制作与视觉包装，确保产出物料严格对齐 **CCTV-13 新闻频道** 的行业顶级播控标准。\n· **优化视觉叙事逻辑：** 在后期包装过程中，通过镜头语言的二次创作，强化报道的感染力，实现了“官方声音”在社交媒体上的**高质感呈现**。",
    outcome: "· **现象级传播数据：** 成功打造单期播放量 **1,500,000+** 的爆款内容，通过高质量动态视觉显著提升了官方账号在年轻受众中的品牌影响力。\n· **权威频道认可：** 作品成功在 **CCTV-13** 频道播出，证明了个人具备在极高工业规范与严苛审核体系下，产出**专业级品牌叙事内容**的实战水准。",
    media: [
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/05%20CUZCCTV/video5_1.mp4', title: '从海上到上海', aspectRatio: '16/9' },
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/05%20CUZCCTV/video5_2.mp4', title: '起底美国疫情真相', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/05%20CUZCCTV/pic5_1.jpg', title: '我从海上到上海', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/05%20CUZCCTV/pic5_2.jpg', title: '我从海上到上海', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/05%20CUZCCTV/pic5_3.jpg', title: '我从海上到上海', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/05%20CUZCCTV/pic5_4.jpg', title: '起底美国疫情真相', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/05%20CUZCCTV/pic5_5.jpg', title: '起底美国疫情真相', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/05%20CUZCCTV/pic5_6.jpg', title: '起底美国疫情真相', aspectRatio: '16/9' },
    ],
  },
  {
    id: "6",
    title: "原神宵宫 MMD：\nUE5 风格化渲染",
    subtitle: "UE5 Rendering",
    category: "Tech Art",
    cover: "https://video.pecoxu.me/d/Portfolio/06%20UE5Rendering/pic6_5.png",
    year: "2025",
    role: "3D 渲染与流程实践",
    challenge:
      "传统 MMD（MikuMikuDance）工具在**光影表现与渲染精度**上难以满足次世代视觉标准。本项目的核心目标是探索如何在保持角色**二次元特征**的同时，引入高表现力的光影层次，提升 **IP 衍生内容**的视觉上限。",
    solution:
      "· **搭建基于 Unreal Engine 5（UE5）的次世代渲染流程：** 打破传统单一工具链，整合 **Blender（布料结算）**与 **UE5（实时渲染）**，成功搭建了一套**接近 PBR 工业标准** 的风格化渲染管线。\n· **实时光影与后处理：** 利用** UE5 Lumen **系统与光线追踪技术增强环境表现，并配合** DaVinci Resolve 与 After Effect **进行影视级调色与视觉特效增强，实现了二次元角色与复杂光影环境的融合。\n· **独立完成从资产处理到后期合成的全过程：** 独立完成模型材质重构、环境搭建及最终后期视觉特效增强，展现了**全流程审美把控力**。",
    outcome: "· **视觉维度突破：** 作品获得 **站酷（Zcool）编辑推荐**，证明了该技术逻辑在风格化渲染与视觉审美上的行业实战价值。\n· **验证了创意生产的高效性：** 通过 **UE5 实时渲染技术**的应用，大幅缩短了高画质视频的渲染周期，为日后大规模生产**高质感营销内容**积累了成熟的技术线路。",
    media: [
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/06%20UE5Rendering/video6_264.mp4', title: 'BDF2023 聚光', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/06%20UE5Rendering/pic6_1.png', title: '人物模型处理', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/06%20UE5Rendering/pic6_2.png', title: '人物材质编辑', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/06%20UE5Rendering/pic6_3.png', title: '烟花添加', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/06%20UE5Rendering/pic6_4.png', title: '后期调色', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/06%20UE5Rendering/pic6_5.png', title: '封面展示', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/06%20UE5Rendering/pic6_6.png', title: '灯光添加', aspectRatio: '16/9' },
    ],
  },
  {
    id: "7",
    title: "原神 宵宫 AI绘画：\n技术管线探索",
    subtitle: "Yoimiya AI: Tech Pipeline Exploration",
    category: "Tech Art",
    cover: "https://video.pecoxu.me/d/Portfolio/07%20AIGC/pic7_6.jpg",
    year: "2024",
    role: "AIGC 节点逻辑搭建",
    challenge: "针对 AIGC 创作中**随机性强、难以精准干预**的痛点，探索如何构建一套满足高精度**视觉一致性**与**确定性产出**的生产管线，以解决**特定 IP 角色**在不同场景下的还原度问题。",
    solution: "· **节点式管线搭建：** 基于 **ComfyUI** 构建**节点化工作流**，实现模型加载、条件控制与图像解码的**模块化管理**，提升了创作过程的可控性。\n· **精准条件控制：** 协同 **ControlNet** 与 **LoRA** 在潜空间实现精准干预，确保对特定 IP 角色与风格的高度还原。\n· **高精度细节重构：** 整合**局部重绘与 4K 超分放大**技术优化视觉细节，确保最终产出符合高精度业内标准。",
    outcome: "· **生产效率飞跃：** 验证了节点式管线的**高度可控性**，大幅缩短了从创意构思到高精度成图的迭代周期。\n· **技术资产标准化：** 积累了可高度复用的**ComfyUI工作流配置文件**，为在日后项目中引入AI 辅助生产提供成熟的技术实践路径。",
    media: [
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/07%20AIGC/pic7_1.PNG', title: '风格引导抽卡', aspectRatio: '9/16' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/07%20AIGC/pic7_2.PNG', title: '构图光影调整', aspectRatio: '9/16' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/07%20AIGC/pic7_3.PNG', title: '构图光影进阶调整', aspectRatio: '9/16' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/07%20AIGC/pic7_4.PNG', title: '细节调整', aspectRatio: '9/16' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/07%20AIGC/pic7_5.PNG', title: 'ControlNet局部重绘', aspectRatio: '9/16' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/07%20AIGC/pic7_6.jpg', title: '超分放大成图', aspectRatio: '9/16' },
    ],
  },
  {
    id: "8",
    title: "守望先锋 花村：\n环境叙事表现",
    subtitle: "Overwatch Hanamura: Environmental Storytelling",
    category: "Tech Art",
    cover: "https://video.pecoxu.me/d/Portfolio/08%20Overwatch/pic8_6.jpg",
    year: "2023",
    role: "地编美术",
    challenge: "基于成熟 IP 地图进行**视觉升级**，在保留原有风格特征的前提下，通过环境物件的**重构与细节填充**，提升场景的**叙事深度与视觉表现力**。",
    solution: "· **地编美术重塑：** 聚焦场景核心区域，通过**季节性贴花**、环境物件的重新布局，丰富了场景的细节厚度与空间叙事感。\n· **动态环境集成：** 利用 **Blueprint（蓝图）** 嵌入动态天气效果、环境音效及VFX 视效，实现了支持第三人称视角跑图的交互式环境。\n· **优化引擎渲染表现：** 针对场景光影进行**重新烘焙与后期处理**，在提升视觉质感的同时，确保了实时渲染环境下的**性能平衡**。",
    outcome: "· **行业与社区认可：** 作品获**站酷编辑推荐**并在 B 站收获 **2.4w+ 播放量**，证明了地编重构作品在核心圈层的审美影响力。\n· **实战管线沉淀：** 完整实践了从美术资源整合到引擎逻辑配置的制作过程，具备构建**高完成度、可运行虚拟场景**的实操能力。",
    media: [
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/08%20Overwatch/video8_1_4k.mp4', title: '守望先锋 花村 场景渲染', aspectRatio: '16/9' },
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/08%20Overwatch/video8_2_4k.mp4', title: '守望先锋 花村 跑图', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/08%20Overwatch/pic8_1.jpg', title: '花村B点 内景', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/08%20Overwatch/pic8_2.jpg', title: '花村B点 内景', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/08%20Overwatch/pic8_3.jpg', title: '花村B点 外景', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/08%20Overwatch/pic8_4.jpg', title: '人物渲染', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/08%20Overwatch/pic8_5.jpg', title: '花村全景渲染', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/08%20Overwatch/pic8_6.jpg', title: '花村庭院渲染', aspectRatio: '16/9' },
    ],
  },
  {
    id: "10",
    title: "明日方舟官网临摹：\n视觉重构练习",
    subtitle: "Arknights UX/UI",
    category: "Interactive",
    cover: "https://video.pecoxu.me/d/Portfolio/10%20Arknights/Cover10.png",
    year: "2023",
    role: "交互设计与视觉重构",
    challenge: "针对移动端官网**信息密度高**、**交互层级复杂**的特征，探索如何利用**数字展示技术**优化视觉呈现，并构建一套逻辑清晰、响应流畅的**交互体验**。",
    solution: "· **交互逻辑重塑：** 利用 **Ventuz** 实时渲染特性，对原官网的角色介绍、势力档案及加载界面进行了深度的**交互复刻与视觉优化**。\n· **多媒介素材集成：** 协同 **Photoshop** 与 **After Effects** 进行视觉素材的二次加工与动态预处理，确保在实时渲染环境下依然具备极高的**视觉还原度**。",
    outcome: "· **专业审美认可：** 作品获得**站酷推荐**，证明了在保持 **IP 风格一致性**的基础上，对复杂交互系统进行重构与视觉优化的专业能力。\n· **技术跨界应用：** 成功将专业数字展示工具（Ventuz）应用于游戏 Web 端交互场景，积累了处理高动态、强交互数字内容的**全流程实战经验**。",
    media: [
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/10%20Arknights/video10_1_4k.mp4', title: '明日方舟官网临摹', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/10%20Arknights/pic10_1.png', title: '网站主页', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/10%20Arknights/pic10_2.png', title: '载入界面', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/10%20Arknights/pic10_3.png', title: '相关势力页面', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/10%20Arknights/pic10_4.png', title: '干员介绍页面', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/10%20Arknights/pic10_5.png', title: '相关档案页面', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/10%20Arknights/pic10_6.jpg', title: '工程截图', aspectRatio: '16/9' },
    ],
  },
  {
    id: "9",
    title: "失落方舟：\n解谜游戏开发实战",
    subtitle: "Game Design Case Study",
    category: "Interactive",
    cover: "https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_5.png",
    year: "2024",
    role: "独立开发",
    challenge: "独立开发语境下构建具备**逻辑闭环**的 3D 交互原型，探索**环境叙事 (Environmental Storytelling)**与**解谜机制**的深度融合。核心难点在于平衡高工业规格的美术表现与交互引导的**确定性产出**。",
    solution: "· **工业级管线整合：** 独立完成从**白盒原型 (Grey Box)**到高精资产的完整闭环，确立了基于 **Cinema 4D** 与 **Substance Painter** 的标准化**PBR 游戏生产开发工作流**。\n· **逻辑驱动叙事：** 利用 **UE4 蓝图** 独立开发含**状态机逻辑**的门禁、电力修复及复活系统，并配合 **Sequencer 动画序列**实现交互与过场动画的无缝衔接。",
    outcome: "· **全周期开发验证：** 通过从 0 到 1的项目实践，积累了在逻辑设计、管线整合及性能平衡方面的综合落地经验。\n· **高质量垂直切片：** 成功交付具备高完成度的**可运行 Demo**，展示了在底层架构构建与**玩家体验设计**上的专业水准。",
    media: [
      { type: 'video', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/video9_1.mp4', title: '实机演示', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_1.png', title: '灵感来源', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_2.png', title: '灰盒搭建', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_3.png', title: '建模过程', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_4.png', title: '场景截图', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_5.png', title: '场景截图', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_6.png', title: '主菜单界面', aspectRatio: '16/9' },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_a.png', title: 'Concept&Narrative', aspectRatio: '16/9', fullWidth: true },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_b.png', title: 'Concept&Narrative', aspectRatio: '16/9', fullWidth: true },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_c.png', title: 'Technical Pipeline&Level Art', aspectRatio: '16/9', fullWidth: true },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_d.png', title: 'Technical Pipeline&Level Art', aspectRatio: '16/9', fullWidth: true },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/pic9_e.png', title: 'Interactive Systems&Logic', aspectRatio: '16/9', fullWidth: true },
      { type: 'image', url: 'https://video.pecoxu.me/d/Portfolio/09%20LostArk/f_Result%206.png', title: 'Result', aspectRatio: '16/9', fullWidth: true },
    ],
  }
];

export const LOGOS = [
  { name: "Logo 1", url: "https://res.cloudinary.com/di8s8kt8a/image/upload/v1772286889/1_iv3eun.png" },
  { name: "Logo 2", url: "https://res.cloudinary.com/di8s8kt8a/image/upload/v1772286890/2_jkqwsr.png" },
  { name: "Logo 3", url: "https://res.cloudinary.com/di8s8kt8a/image/upload/v1772286891/3_ooq6vo.png" },
  { name: "Logo 4", url: "https://res.cloudinary.com/di8s8kt8a/image/upload/v1772286891/4_sicb57.png" },
  { name: "Logo 5", url: "https://res.cloudinary.com/di8s8kt8a/image/upload/v1772286891/5_saljew.png" },
  { name: "Logo 6", url: "https://res.cloudinary.com/di8s8kt8a/image/upload/v1772286893/6_juc05a.png" },
  { name: "Logo 7", url: "https://res.cloudinary.com/di8s8kt8a/image/upload/v1772286890/7_ezpmin.png" }
];
